# YOLO Dataset Configuration
# Relative path from this file (configs/data.yaml) to the dataset folder
path: ../data/dataset
train: images/train
val: images/val
test:  # optional

# Classes
names:
  1: container_code
