# YOLO Dataset Configuration
# Relative path from this file (configs/data.yaml) to the dataset folder
path: ../data/dataset/dataset260121_1804
train: images/train
val: images/val
test:  # optional

# Classes
names:
  0: truck
  1: container
  2: code_area